apiVersion: v1
kind: Service
metadata:
  name: unbound
spec:
  clusterIP: 10.43.0.2
  selector:
    app: unbound
  ports:
    - protocol: TCP
      port: 5335
      targetPort: 53
      name: tcpport
    - protocol: UDP
      port: 5335
      targetPort: 53  
      name: udpport
